FROM python:3.9-slim
WORKDIR /app
RUN pip install --no-cache-dir pytest
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY tests.py .
COPY populate.py .
CMD ["sh", "-c", "python populate.py && python -m unittest tests.py"]
